let codComposicao = 1;

describe('Usuários devem realizar o login', () => {
  context('Login de Usuários', () => {
    beforeEach(() => {
      codComposicao++,
      cy.sessionLogin()
      cy.visit('/home')
      cy.viewport(1280, 720) //Configuração do tamanho da tela
    })
    Cypress.on('uncaught:exception', (err, runnable) => {
      return false
    })
    it('Criando Etapas no orçamento', () => { //Login com senha correta      
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938') //Em Producao: 688cafbb04184fb8b083ad95       Em Teste:68af5bbecab727f01b964938 
      cy.wait(1000)
      cy.get('.add_phase_end').click()

      cy.get('.td_descr > .form-control').type('Serviços Preliminares')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('Fundações')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('PAV - 1')
      cy.get('.salvar_new_etapa > .material-icons').click()
      
      cy.get('.add_phase_end').type('Pisos')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1')
      cy.get('.salvar_new_etapa > .material-icons').click()
      
      cy.get('.add_phase_end').type('Paredes')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2')
      cy.get('.salvar_new_etapa > .material-icons').click()
      
      cy.get('.add_phase_end').type('Esquadrias')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3')
      cy.get('.salvar_new_etapa > .material-icons').click()
      
      cy.get('.add_phase_end').type('PAV - 2')
      cy.get('.salvar_new_etapa > .material-icons').click()
      
      cy.get('.add_phase_end').type('Pisos')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1')
      cy.get('.salvar_new_etapa > .material-icons').click()

      cy.get('.add_phase_end').type('Paredes')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2')
      cy.get('.salvar_new_etapa > .material-icons').click()

      cy.get('.add_phase_end').type('Esquadrias')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3')
      cy.get('.salvar_new_etapa > .material-icons').click()
    })

    it('Adicionando Composições no Orçamento', () => {

      cy.visit('orc/orcamentos/68af5bbecab727f01b964938') //ALTERAR ID DO ORCAMENTO
      cy.wait(1000)

      //000662
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SBC')
      cy.get('.td_code > .form-control').type('000662')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //73859
      //cy.wait(2000)
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type(randomValue)
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //98458
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type(randomValue)
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //98681
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SBC')
      cy.get('.td_code > .form-control').type('011094')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //15.05.520
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CPOS')
      cy.get('.td_code > .form-control').type('15.05.520')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //89488
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type(randomValue)
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //011094
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SBC')
      cy.get('.td_code > .form-control').type('011094')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //90930
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //87259
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //15.05.520
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CPOS')
      cy.get('.td_code > .form-control').type('15.05.520')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //89467
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //87905
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //87543
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2.4')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //91328
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //94570
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //94559
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //99837
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3.4')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //011094
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SBC')
      cy.get('.td_code > .form-control').type('011094')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //90930
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //87259
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //15.05.520
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CPOS')
      cy.get('.td_code > .form-control').type('15.05.520')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click() 
      cy.get('.td_code > .form-control').type('{enter}')

      //89467
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //87905
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //87543
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2.4')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //91328
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //94570
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //94559
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //99837
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type()
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3.4')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')
    })

    it('Aplicação de BDI', () =>{
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938')
      cy.get('#budget_config_bdi > th.tx-right > a').click()
      cy.wait(1000)
      cy.get('#bdi_manual').click()
      cy.wait(1000)
      cy.get('#\\30 ').type('25\,01')
      cy.wait(1000)
      cy.get('.form-bdi > .modal-content > .modal-footer > .btn-primary').click()
    })

    it('Retirando BDI', () => {
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938')
      cy.get('#budget_config_bdi > th.tx-right > a').click()
      cy.get('#\\30 ').clear()
      cy.get('.form-bdi > .modal-content > .modal-footer > .btn-primary').click()
    })

    it('Apagando o orçamento', () => {
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938')
      cy.get('#th_items_selection').click()
      cy.contains('a', '000662').rightclick()
      cy.get('.items_delete_all > .bg-resource').click()
    })

    it('Acessando composições de todos bancos', () => {

      //SINAPI
      cy.get(':nth-child(3) > .with-sub').click()
      cy.get(':nth-child(3) > .nav-sub > :nth-child(1) > .nav-link').click()
      cy.get('.blue-box').click()
      cy.get('#sinapi_data_select').select('07/2025')
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(3) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SBC
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#sbc_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(8) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-3').click()
      cy.get(':nth-child(15) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SICRO3
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#sicro3_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get('.breadcrumbs > :nth-child(2)').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(3) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SETOP
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#setop_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(9) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(5) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //IOPES
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#iopes_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(18) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(15) > .codigo > .link-codigo > a').click()
      cy.get('.breadcrumbs > :nth-child(2)').click()

      //SIURB
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#siurb_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(22) > .codigo > .link-codigo').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-3').click()
      cy.get(':nth-child(14) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SIURB INFRA
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#siurb_infra_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(25) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(13) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SUDECAP
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#sudecap_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(13) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //CPOS
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#cpos_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(2) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(4) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-3').click()
      cy.get(':nth-child(11) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //FDE
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#fde_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(6) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(24) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(13) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //EMOP
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#emop_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(5) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(20) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(10) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //ORSE
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#orse_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(13) > .codigo > .link-codigo').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(8) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SICRO2
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#sicro_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(5) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(28) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(15) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SEINFRA
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#seinfra_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(8) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(16) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-3').click()
      cy.get(':nth-child(12) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //CAEMA
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#caema_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(4) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(30) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(15) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //EMBASA
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#embasa_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(6) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(15) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //CAERN
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#caern_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(5) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(13) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //COMPESA
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#compesa_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(8) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(19) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //AGESUL
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#agesul_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(6) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(25) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(10) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //AGETOP CIVIL
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#agetop_civil_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(4) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(30) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(16) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //AGETOP RODOVIARIA
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#agetop_rodoviaria_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(4) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(12) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SEDOP
      cy.get('.blue-box').click()
      cy.get('#unselect-all-checkboxes').click()
      cy.get('#sedop_checkbox').click()
      cy.get('#submit-btn-modal').click()
      cy.get(':nth-child(4) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(29) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()
      cy.get('#submit-btn').click()
      cy.get(':nth-child(1) > .pagination-custom > #nav-page-items > #nav-page-2').click()
      cy.get(':nth-child(12) > .codigo > .link-codigo > a').click()
      cy.get(':nth-child(2) > a > .flaticon-bricks3').click()

      //SOLICITAR AO MAUMAU NA SEGUNDA PARA QUE ELE SUBA A BASE DERPR NO TESTE
    })

    it('Criando uma composicao propria com todos bancos (SINAPI - TRUNCAR - MAO DE OBRA)', () => {
      cy.get(':nth-child(3) > .with-sub').click()
      cy.get(':nth-child(3) > .nav-sub > :nth-child(2) > .nav-link').click()
      cy.get('[name="banco_emp_composicao[codigo]"]').clear()
      cy.get('[name="banco_emp_composicao[codigo]"]').type('Teste Composicao Automatizada SINAPI 1')
      cy.get('[name="banco_emp_composicao[c2]"]').type('Teste Composicao Automatizada SINAPI 1')
      cy.get('[name="banco_emp_composicao[descricao]"]').type('Teste Composicao Automatizada SINAPI 1')
      cy.get('[name="banco_emp_composicao[unidade]"]').type('m2')
      cy.get('#banco_emp_composicao_mao_de_obra').click()
      cy.get('[name="banco_emp_composicao[observacao]"]').type('Teste Composicao Automatizada SINAPI 1')
      cy.get('.justify-content-end > .btn').click()
      cy.get('#nacional-coverage').click()
      cy.get('#sudeste-coverage').click()
      cy.get('#nordeste-coverage').click()
      cy.get('#centro-oeste-coverage').click()
      cy.get('#norte-coverage').click()
      cy.get('#sul-coverage').click()
      cy.get('[name="commit"]').click()
    })

    it('Adicionando Composicoes Auxiliares de todos os bancos e entrando nelas', () => {
      cy.get(':nth-child(3) > .with-sub').click()
      cy.get(':nth-child(3) > .nav-sub > :nth-child(1) > .nav-link').click()
      cy.get(':nth-child(3) > [name="bases[emp][selected]"]').click()
      cy.get('#submit-btn').click()
      cy.get('.link-codigo > a').click()
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()

      //COMP. AUXILIAR SINAPI
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(2) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP. AUXILIAR SBC
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SBC')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(2) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SICRO3
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SICRO3')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(3) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SICRO2
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SICRO2')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(4) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR ORSE
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('ORSE')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(5) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SEDOP
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SEDOP')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(6) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SEINFRA
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SEINFRA')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(7) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SETOP
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SETOP')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(8) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR IOPES
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('IOPES')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(9) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SIURB
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SIURB')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(10) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SIURB INFRA
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SIURB INFRA')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(11) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SUDECAP
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SUDECAP')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(12) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR CPOS
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('CPOS')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(13) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR FDE
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('FDE')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(14) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR AGESUL
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('AGESUL')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(15) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR AGETOP CIVIL
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('AGETOP CIVIL')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(16) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR AGETOP RODOVIARIA
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('AGETOP RODOVIARIA')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(17) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR CAEMA
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('CAEMA')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(18) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR EMBASA
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('EMBASA')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(19) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR CAERN
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('CAERN')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(20) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR COMPESA
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('COMPESA')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(21) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR EMOP
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('EMOP')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(22) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()

      //COMP.AUXILIAR SCO
      cy.get('#insert-new-item-buttons > .row > :nth-child(1) > .btn').click()
      cy.get('[name="base"]').select('SCO')
      cy.get('[id^=query_code_row]').type('10')
      cy.get('tbody > :nth-child(23) > :nth-child(4)').click()
      cy.get('[id^=query_qty_row]').type('1')
      cy.get('.bg-transparent > .material-icons').click()
    })

    it('Excluindo composição própria', () => {
      cy.get(':nth-child(3) > .with-sub').click()
      cy.get(':nth-child(3) > .nav-sub > :nth-child(1) > .nav-link').click()
      cy.get('#query_placeholder').type('Teste Composicao Automatizada SINAPI 1')
      cy.get('#propria-radio').click()
      cy.get('#submit-btn').click()
      cy.get('.link-codigo > a').click()
      cy.get(':nth-child(2) > #navbarDropdown').click({force: true}) // SELECIONANDO OPÇÃO EM HOVER
      cy.get('[data-confirm="Você tem certeza que quer Apagar esta Composição?"]').click()
    })

    it('Adicionando etapas de todos itens', () => { //Login com senha correta
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938') //Em Producao: 688cafbb04184fb8b083ad95       Em Teste:68af5bbecab727f01b964938 
      cy.wait(1000)
      
      cy.get('.add_phase_end').click()
      cy.get('.td_descr > .form-control').type('NACIONAL')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SINAPI')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.1')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SICRO3')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.2')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SBC')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.3')
      cy.get('.salvar_new_etapa > .material-icons').click() 

      cy.get('.add_phase_end').click()
      cy.get('.td_descr > .form-control').type('SUDESTE')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SETOP')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.1')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('IOPES')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.2')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SIURB')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.3')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SIURB INFRA')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.4')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SUDECAP')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.5')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('CPOS')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.6')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('FDE')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.7')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('EMOP')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.8')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SCO')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.9')
      cy.get('.salvar_new_etapa > .material-icons').click()

      cy.get('.add_phase_end').click()
      cy.get('.td_descr > .form-control').type('NORDESTE')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('ORSE')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SEINFRA')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('CAEMA')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('EMBASA')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.4')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('CAERN')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.5')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('COMPESA')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.6')
      cy.get('.salvar_new_etapa > .material-icons').click()

      cy.get('.add_phase_end').click()
      cy.get('.td_descr > .form-control').type('CENTRO OESTE')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('AGESUL')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('AGETOP CIVIL')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('AGETOP RODOVIARIA')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3')
      cy.get('.salvar_new_etapa > .material-icons').click()

      cy.get('.add_phase_end').click()
      cy.get('.td_descr > .form-control').type('NORTE')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('SEDOP')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('5.1')
      cy.get('.salvar_new_etapa > .material-icons').click()

      cy.get('.add_phase_end').click()
      cy.get('.td_descr > .form-control').type('SUL')
      cy.get('.salvar_new_etapa > .material-icons').click()
      cy.get('.add_phase_end').type('DERPR')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('6.1')
      cy.get('.salvar_new_etapa > .material-icons').click()
    })

    it('Adicionando Composições no Orçamento', () => {
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938') //ALTERAR ID DO ORCAMENTO
      cy.wait(1000)

      //SINAPI
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type('92354')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type('97478')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SINAPI')
      cy.get('.td_code > .form-control').type('101402')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SICRO3
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SICRO3')
      cy.get('.td_code > .form-control').type('0308259')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.2.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SICRO3')
      cy.get('.td_code > .form-control').type('0407819')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.2.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SICRO3')
      cy.get('.td_code > .form-control').type('0605658')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.2.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

     //SBC
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SBC')
      cy.get('.td_code > .form-control').type('000662') //NÃO TIRAR ESSA COMP POIS ELA SERVE PARA O TESTE DE EXCLUSÃO DO ORÇAMENTO AO CLICAR COM O BOTÃO DIREITO
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.3.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SBC')
      cy.get('.td_code > .form-control').type('120409')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.3.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SBC')
      cy.get('.td_code > .form-control').type('120441')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('1.3.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SETOP
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SETOP')
      cy.get('.td_code > .form-control').type('CO-27396')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SETOP')
      cy.get('.td_code > .form-control').type('ED-13281')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click() 
      cy.get('#select_input_bases').select('SETOP')
      cy.get('.td_code > .form-control').type('RO-00052')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //IOPES
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('IOPES')
      cy.get('.td_code > .form-control').type('020710')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.2.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('IOPES')
      cy.get('.td_code > .form-control').type('090206')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.2.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('IOPES')
      cy.get('.td_code > .form-control').type('061901')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.2.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SIURB
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SIURB')
      cy.get('.td_code > .form-control').type('7001048')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.3.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SIURB')
      cy.get('.td_code > .form-control').type('8001004')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.3.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SIURB')
      cy.get('.td_code > .form-control').type('8001080')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.3.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SIURB INFRA
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SIURB INFRA')
      cy.get('.td_code > .form-control').type('6065008')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.4.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SIURB INFRA')
      cy.get('.td_code > .form-control').type('7031000')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.4.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SIURB INFRA')
      cy.get('.td_code > .form-control').type('8035000')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.4.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SUDECAP
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SUDECAP')
      cy.get('.td_code > .form-control').type('01.01.21')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.5.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SUDECAP')
      cy.get('.td_code > .form-control').type('01.09.15')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.5.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SUDECAP')
      cy.get('.td_code > .form-control').type('02.02.05')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.5.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //CPOS
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CPOS')
      cy.get('.td_code > .form-control').type('04.11.060')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.6.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CPOS')
      cy.get('.td_code > .form-control').type('06.11.060')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.6.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CPOS')
      cy.get('.td_code > .form-control').type('21.01.100')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.6.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //FDE
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('FDE')
      cy.get('.td_code > .form-control').type('06.03.087')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.7.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('FDE')
      cy.get('.td_code > .form-control').type('06.01.006')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.7.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('FDE')
      cy.get('.td_code > .form-control').type('07.03.132')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.7.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //EMOP
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('EMOP')
      cy.get('.td_code > .form-control').type('15.036.0079-A')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.8.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('EMOP')
      cy.get('.td_code > .form-control').type('15.036.0062-A')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.8.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('EMOP')
      cy.get('.td_code > .form-control').type('15.036.0076-A')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.8.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SCO
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SCO')
      cy.get('.td_code > .form-control').type('AD 14.12.0050')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.9.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SCO')
      cy.get('.td_code > .form-control').type('AD 14.15.0770')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.9.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SCO')
      cy.get('.td_code > .form-control').type('EQ 25.05.0150')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('2.9.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //ORSE
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('ORSE')
      cy.get('.td_code > .form-control').type('10067')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('ORSE')
      cy.get('.td_code > .form-control').type('10516')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('ORSE')
      cy.get('.td_code > .form-control').type('13484')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SEINFRA
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SEINFRA') 
      cy.get('.td_code > .form-control').type('C1802')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SEINFRA')
      cy.get('.td_code > .form-control').type('C4962')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SEINFRA')
      cy.get('.td_code > .form-control').type('C4550')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.2.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //CAEMA
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CAEMA')
      cy.get('.td_code > .form-control').type('090501')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CAEMA')
      cy.get('.td_code > .form-control').type('171304')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CAEMA')
      cy.get('.td_code > .form-control').type('110231')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.3.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //EMBASA
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('EMBASA')
      cy.get('.td_code > .form-control').type('09.96.10')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.4.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('EMBASA')
      cy.get('.td_code > .form-control').type('09.95.82')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.4.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('EMBASA')
      cy.get('.td_code > .form-control').type('09.95.50')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.4.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //CAERN
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CAERN')
      cy.get('.td_code > .form-control').type('1020042')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.5.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CAERN')
      cy.get('.td_code > .form-control').type('2040106')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.5.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('CAERN')
      cy.get('.td_code > .form-control').type('1020044')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.5.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //COMPESA
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('COMPESA')
      cy.get('.td_code > .form-control').type('02.02.12U')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.6.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('COMPESA')
      cy.get('.td_code > .form-control').type('02.05.01U')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.6.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('COMPESA')
      cy.get('.td_code > .form-control').type('22.03.14U')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('3.6.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //AGESUL
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGESUL')
      cy.get('.td_code > .form-control').type('0101001128')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGESUL')
      cy.get('.td_code > .form-control').type('0101002100')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGESUL')
      cy.get('.td_code > .form-control').type('0201003016')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //AGETOP CIVIL
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGETOP CIVIL')
      cy.get('.td_code > .form-control').type('021003')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGETOP CIVIL')
      cy.get('.td_code > .form-control').type('051023')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGETOP CIVIL')
      cy.get('.td_code > .form-control').type('070353')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.2.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //AGETOP RODOVIARIA
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGETOP RODOVIARIA')
      cy.get('.td_code > .form-control').type('40315')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGETOP RODOVIARIA')
      cy.get('.td_code > .form-control').type('45144')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('AGETOP RODOVIARIA')
      cy.get('.td_code > .form-control').type('41308')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('4.3.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //SEDOP
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SEDOP')
      cy.get('.td_code > .form-control').type('280014')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('5.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SEDOP')
      cy.get('.td_code > .form-control').type('200000')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('5.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('SEDOP')
      cy.get('.td_code > .form-control').type('020842')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('5.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      //DERPR
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('DERPR')
      cy.get('.td_code > .form-control').type('603000')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('6.1.1')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('DERPR')
      cy.get('.td_code > .form-control').type('707000')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('6.1.2')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')

      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('#select_input_bases').select('DERPR')
      cy.get('.td_code > .form-control').type('813450')
      cy.get('.td_itemization > .form-control').clear()
      cy.get('.td_itemization > .form-control').type('6.1.3')
      cy.get('.td_qty > .form-control').type('1')
      cy.get('[id^=tr_ml]').click()
      cy.get('.td_code > .form-control').type('{enter}')
    })

    it('Apagando o orçamento', () => {
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938')
      cy.get('#th_items_selection').click()
      cy.contains('a', '2040106').rightclick()
      cy.get('.items_delete_all > .bg-resource').click()
    })

    it('Teste de Array adicionando em uma composição', () => {

      const testeComposicoes = ['92354', '97503', '95384', '88264', '101408', '88281', '101422', '101431'];
      const testeComposicoesUsar = testeComposicoes[Math.floor(Math.random() * testeComposicoes.length)]
      
      cy.visit('orc/orcamentos/68af5bbecab727f01b964938')
      cy.wait(1000)
      cy.get(':nth-child(2) > .dropdown > .add_item_end').click()
      cy.get('.td_code > .form-control').type(testeComposicoesUsar)
    })
    
  })
})